apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gzws
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0025-tenant/tkrw-pr712-0075-0025-app/devfile-sample-gzws@sha256:5fac72314921f5bae73a0a5dbb5c1718ff9fb0d85953610aa23870c5e82dfacc
        name: my-nodejs
        resources: {}
status: {}
